import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./core/component/header/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Điện lạnh Kim Phú",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {children}
        <footer></footer>
      </body>
    </html>
  );
}
